export default defineEventHandler(() => {

  const data = [
    {
      current_page: 1,
      data: [
        { id: 441,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "99": "その他" },
          name: "DMリスト作成テスト",
          request_team: { "consul-nagoya-team": "名古屋T", "consul-tokyo-team": "東京T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他１",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-20T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 442,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "00": "工業" },
          name: "DMリスト作成テスト",
          request_team: {  "consul-tokyo-team": "東京T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他２",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-21T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 443,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "77": "コンサル" },
          name: "DMリスト作成テスト",
          request_team: { "consul-hokkaido-team": "北海道T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他２",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-22T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 444,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 445,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 446,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 447,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 448,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 449,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
        { id: 450,
          created_by: { "1": "武元 義幸" },
          areas: [ "中部" ],
          area_memo: "名古屋",
          category: null,
          industry_memo: "その他",
          jmss_industries: { "01": "建設" },
          name: "DMリスト作成テスト",
          request_team: { "consul-kusyu-team": "九州T" },
          call_team: null,
          request_users: { "1": "武元 義幸" },
          notification_users: null,
          type: "その他３",
          confirmations: null,
          method: "DM",
          dm_date: "2023-07-20",
          vender_name: null,
          note: "テスト",
          parent_id: 440,
          sales_ranges: [ "0～50百万円未満" ],
          created_at: "2023-07-23T23:16:57",
          updated_at: "2023-07-20T23:16:57",
          deleted_at: null
        },
      ],
      first_page_url: "https://intra.dev.jms-support.jp/api/v1/approach_lists?key=Zpi5G7ugxYUHGL7MiAKpYmN5MDjLSiV8fUQY2jJD7DkuCESzKrJAzQW8uazJEM6h&page=1",
      from: 1,
      last_page:210,
      next_page_url: "https://intra.dev.jms-support.jp/api/v1/approach_lists?key=Zpi5G7ugxYUHGL7MiAKpYmN5MDjLSiV8fUQY2jJD7DkuCESzKrJAzQW8uazJEM6h&page=2",
      path: "https://intra.dev.jms-support.jp/api/v1/approach_lists",
      per_page: 15,
      prev_page_url: null,
      to: 15,
      total: 10
    },
  ]

    return data

  });
  