export default defineEventHandler(() => {

    const data = [
      { id: 441,
        created_by: { "1": "武元 義幸" },
        areas: [ "中部" ],
        area_memo: "名古屋",
        category: null,
        industry_memo: "その他",
        jmss_industries: { "99": "その他" },
        name: "DMリスト作成テスト",
        request_team: { "consul-nagoya-team": "名古屋T" },
        call_team: null,
        request_users: { "1": "武元 義幸" },
        notification_users: null,
        type: "その他１",
        confirmations: null,
        method: "DM",
        dm_date: "2023-07-20",
        vender_name: null,
        note: "テスト",
        parent_id: 440,
        sales_ranges: [ "0～50百万円未満" ],
        created_at: "2023-07-20T23:16:57",
        updated_at: "2023-07-20T23:16:57",
        deleted_at: null
      },
      { id: 441,
        created_by: { "1": "武元 義幸" },
        areas: [ "中部" ],
        area_memo: "名古屋",
        category: null,
        industry_memo: "その他",
        jmss_industries: { "99": "その他" },
        name: "DMリスト作成テスト",
        request_team: { "consul-nagoya-team": "名古屋T" },
        call_team: null,
        request_users: { "1": "武元 義幸" },
        notification_users: null,
        type: "その他２",
        confirmations: null,
        method: "DM",
        dm_date: "2023-07-20",
        vender_name: null,
        note: "テスト",
        parent_id: 440,
        sales_ranges: [ "0～50百万円未満" ],
        created_at: "2023-07-20T23:16:57",
        updated_at: "2023-07-20T23:16:57",
        deleted_at: null
      },
      { id: 441,
        created_by: { "1": "武元 義幸" },
        areas: [ "中部" ],
        area_memo: "名古屋",
        category: null,
        industry_memo: "その他",
        jmss_industries: { "99": "その他" },
        name: "DMリスト作成テスト",
        request_team: { "consul-nagoya-team": "名古屋T" },
        call_team: null,
        request_users: { "1": "武元 義幸" },
        notification_users: null,
        type: "その他２",
        confirmations: null,
        method: "DM",
        dm_date: "2023-07-20",
        vender_name: null,
        note: "テスト",
        parent_id: 440,
        sales_ranges: [ "0～50百万円未満" ],
        created_at: "2023-07-20T23:16:57",
        updated_at: "2023-07-20T23:16:57",
        deleted_at: null
      },
    ]
  
      return data
  
    });
    