export default defineEventHandler(() => {

  const data = [
    { 
      masterId: 111,
      companyName: 'コムコシステム',
      representativeName: 'コムコ太郎',
      postCode: '111-1111',
      address: '東京都品川区東五反田３丁目２０−１４',
      sales: 200,
      operatingIncome: null,
      industry1: 'システム開発1',
      industry2: 'システム開発2',
      industry3: 'システム開発3',
      businessItems: 'システム',
      representativeAge: 59, 
      numberOfEmployee: 150,
      matchingResult: 111
    },
    { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },    
      { 
      masterId: 222,
      companyName: '株式会社〇〇',
      representativeName: '〇〇太郎',
      postCode: '222-2222',
      address: '東京都品川区東五反田３丁目２０−１2',
      sales: 500,
      operatingIncome: 1000,
      industry1: 'コンサルティング1',
      industry2: 'コンサルティング2',
      industry3: 'コンサルティング3',
      businessItems: 'コンサルティング',
      representativeAge: 60, 
      numberOfEmployee: 300,
      matchingResult: 222
      },
    ]

    return data

  });




  