export default defineEventHandler(() => {

  const data = [
    { id: 441,
      registrationDate: '2022-11-05',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング中" 
    },
    { id: 442,
      registrationDate: '2022-12-10',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 443,
      registrationDate: '2022-12-15',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 445,
      registrationDate: '2022-12-20',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 446,
      registrationDate: '2022-12-25',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 447,
      registrationDate: '2022-12-30',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 448,
      registrationDate: '2023-01-05',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 449,
      registrationDate: '2023-01-20',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 450,
      registrationDate: '2023-01-15',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 451,
      registrationDate: '2023-01-10',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
      },
    ]
    return data
  });
  