export default defineEventHandler(() => {

  const data = [
    { id: 441,
      registrationDate: '2022-11-05',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング中",
      created_by: { "1": "テスト　太郎" },
    },
    { id: 442,
      registrationDate: '2022-12-10',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み",
      created_by: { "2": "テスト　次郎" },
    },
    { id: 443,
      registrationDate: '2022-12-15',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "3": "テスト　三郎" },
    },
    { id: 445,
      registrationDate: '2022-12-20',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "5": "テスト　五郎" },
    },
    { id: 446,
      registrationDate: '2022-12-25',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "6": "テスト　六郎" },
    },
    { id: 447,
      registrationDate: '2022-12-30',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "7": "テスト　七郎" },
    },
    { id: 448,
      registrationDate: '2023-01-05',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "8": "テスト　八郎" },
    },
    { id: 449,
      registrationDate: '2023-01-20',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "9": "テスト　九郎" },
    },
    { id: 450,
      registrationDate: '2023-01-15',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "10": "テスト　十郎" },
    },
    { id: 451,
      registrationDate: '2023-01-10',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" ,
      created_by: { "11": "テスト　十一郎" },
      },
    ]
    return data
  });
  