export default defineEventHandler(() => {

  const data = [
    { id: 1,
      registrationDate: '2022-11-11',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング中" 
    },
    { id: 2,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 3,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 4,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 5,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 6,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 7,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 8,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 9,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
    },
    { id: 10,
      registrationDate: '2022-12-12',
      sendMailDate: '2022-11-11',
      sendCompanyCount: 1000,
      listName: "買_不動産_福井202303",
      approachPurpose: "売り打診",
      chargeOfTeam: "ダイレクト",
      chargeOfConsultant: "比留間健",
      ompanyIndustry: "不動産",
      companyRegion: "北陸",
      companySales: "0～50百万円",
      matchingStatus: "マッチング済み" 
      },
    ]
    return data
  });
  